import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.WindowConstants;

public class EliminarElementos extends javax.swing.JFrame {

    private Institucion institucion;
    BufferedReader lector = new BufferedReader ( new InputStreamReader (System.in) );
    
    public EliminarElementos(Institucion institucion) {
        
        initComponents();
        
        /* Establecemos el tamaño de la ventana , la centramos, el título y terminar la ejecución del programa si la ventana se cierra. */
        setSize(500,500);
        setLocationRelativeTo(null);
        setTitle("Eliminar Elementos");
        this.getContentPane().setBackground(Color.PINK);
        this.institucion = institucion;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        eliminarAlumno = new javax.swing.JButton();
        eliminarAsignatura = new javax.swing.JButton();
        eliminarRecDigital = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Seleccione una opción:");

        eliminarAlumno.setText("1.- Eliminar Alumno");
        eliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAlumnoActionPerformed(evt);
            }
        });

        eliminarAsignatura.setText("2.- Eliminar Asignatura");
        eliminarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAsignaturaActionPerformed(evt);
            }
        });

        eliminarRecDigital.setText("3.- Eliminar Recurso Digital");
        eliminarRecDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRecDigitalActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarAlumno)
                            .addComponent(eliminarAsignatura)
                            .addComponent(eliminarRecDigital))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarAsignatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarRecDigital)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void eliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAlumnoActionPerformed

        if(institucion.existenAsignaturas()==false){
            System.out.println("La institucion no posee asignaturas y por lo tanto no hay alumnos para eliminar.\n");
            return;
        }
        
        System.out.println("\nIngrese la sigla de la Asignatura: ");
        String siglaAsig = null;
        try {
            siglaAsig = lector.readLine();
        } catch (IOException ex) {
            Logger.getLogger(AgregarElementos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while (institucion.buscarAsignatura(siglaAsig) == null){
            System.out.println("Inténtelo nuevamente. Ingrese una sigla válida. ");
            try {
                siglaAsig = lector.readLine();
            } catch (IOException ex) {
                Logger.getLogger(AgregarElementos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        Asignatura asig = institucion.buscarAsignatura(siglaAsig);
        
        if (asig.existenAlumnos() == false){
            System.out.println("\nNo hay alumnos registrados.\n");
        }
        else{
            System.out.println("Ingrese rut del alumno, de la forma '12.345.678-9'.");
            String rut = null;
            try {
                rut = lector.readLine();
            } catch (IOException ex) {
                Logger.getLogger(EliminarElementos.class.getName()).log(Level.SEVERE, null, ex);
            }
            asig.eliminarDato(rut, 1);
        }

    }//GEN-LAST:event_eliminarAlumnoActionPerformed

    private void eliminarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAsignaturaActionPerformed
        if (institucion.existenAsignaturas() == false){
            System.out.println("\nNo hay asignaturas registradas.\n");
        }
        else{
            System.out.println("Ingrese sigla de la asignatura");
            String sigla = null;
            try {
                sigla = lector.readLine();
            } catch (IOException ex) {
                Logger.getLogger(EliminarElementos.class.getName()).log(Level.SEVERE, null, ex);
            }
            institucion.eliminarDato(sigla, 1);
        }
    }//GEN-LAST:event_eliminarAsignaturaActionPerformed

    private void eliminarRecDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRecDigitalActionPerformed
        
        if (institucion.existenAsignaturas() == false){
            System.out.println("\nNo hay asignaturas registradas, por lo tanto, no existen recursos digitales.\n");
        }
        else{
            Asignatura auxAsignatura;
            System.out.println("Ingrese la sigla de la Asignatura que desea ver los Recursos Digitales: ");
            String sigla = null;
            try {
                sigla = lector.readLine();
            } catch (IOException ex) {
                Logger.getLogger(EliminarElementos.class.getName()).log(Level.SEVERE, null, ex);
            }

            while (institucion.buscarAsignatura(sigla) == null){
                System.out.println("Inténtelo nuevamente. Ingrese una sigla válida. ");
                try {
                    sigla = lector.readLine();
                } catch (IOException ex) {
                    Logger.getLogger(EliminarElementos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            auxAsignatura = institucion.buscarAsignatura(sigla);
            System.out.println("Ingrese el nombre del Recurso Digital: ");
            String nombre = null;
            try {
                nombre = lector.readLine();
            } catch (IOException ex) {
                Logger.getLogger(EliminarElementos.class.getName()).log(Level.SEVERE, null, ex);
            }
            auxAsignatura.eliminarDato(nombre);
        }
        
    }//GEN-LAST:event_eliminarRecDigitalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton eliminarAlumno;
    private javax.swing.JButton eliminarAsignatura;
    private javax.swing.JButton eliminarRecDigital;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JButton salir;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
